version: '3'
services:
  flutter:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash -c "fvm flutter run -d web-server --web-hostname 0.0.0.0 --web-port 8080"
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
